### PR TITLE
fix/Support white spaces in path for system URI registration

### PR DESCRIPTION
**Pull request by bochaco**
This PR depends on the following PR in system_uri lib which makes the necessary adjustments to accept the system URI's exec command as an arguments array: https://github.com/maidsafe/system_uri/pull/36

### CODE REVIEW

**Review by hunterlester — CHANGES_REQUESTED** [review]
Here's what the registration path looks like on Windows:
`""C:\Users\guilf\safe\dev\peruse\release\win-unpacked\Peruse.exe"" "%1"`

There are an extra set of quotes around app path. System isn't able to properly open Peruse with this path.

**Comment by bochaco** [comment]
Thanks @hunterlester , it seems we'll need to have system_uri to support the exec command as an array of args then.

**Review by hunterlester — APPROVED** [review]
Tested on Windows

**Review by joshuef — APPROVED** [review]

**Review by hunterlester — APPROVED** [review]
Success on Windows with white space in executable path.

**Comment by bochaco** [comment]
This is working fine on Linux as well.

**Pull request merged**
