### PR TITLE
feat/save-read: Save and read the state to the network 

### PR DESCRIPTION
**Pull request by joshuef**
via shortcut commands in `File` menu.

Adds in store state and actions to trigger save/read, as well as relevant tests.

### CODE REVIEW

**Review by hunterlester — DISMISSED** [review]
I see file options now and am successfully saving and reading browser state to and from network.

Perhaps the last thing that's needed is to inform user with a message that they need to sign in to network to successfully save state, if they make a save attempt while logged out.

image

**Comment by bochaco** [comment]
I tried to read the state for the very first time before ever saving it, and there is an error thrown from safe_app libs as expected, but I think we should handle the error:
```
Unhandled Rejection. Reason: -106: Core error: Routing client error -> Requested entry not found
At: Promise {
  <rejected> Error: -106: Core error: Routing client error -> Requested entry not found
    at /home/bochaco/work/bochaco-peruse/app/extensions/safe/index.js:152:27
    at <anonymous> }
```

Also, there is an issue when you save the state before you read it from the network e.g. if you log in, and right after it save the state (which has not bookmarks or history), it then overwrites previous data/state. We will have to probably read before saving it behind the scenes to support a merge. Alternatively have it as in beaker to read state automatically upon logging in. At the end of the day, I think all these options should go into a settings page for the user to customise the preferred behaviour.

I tried to log out and the history & bookmarks are not cleared from the bookmarks/history pages, even if I close them and open them up again.

Another minor thing, links in history and bookmarks pages don't work for me, I do see they have the `href` though: `<a href="safe://ddddd">safe://ddddd</a>`.

I know this PR is not meant to add UX/UI enhancements, but for when we work on it, I think having a loading icon in the bookmarks/history pages when it's reading the state will make a big difference.

**Comment by safesurfer** [comment]
I am able to save and read the browser state. The bookmark and history items are same, even though I logout and login with different credentials. logout doesn't clear the list.
It is ok, if I restart the browser.

**Comment by joshuef** [comment]
History/bookmarks are sorted 👍 , as is the initial read without data (now shows an error).

I don't think we should have auto-read yet, @bochaco as the use will just be hit with an auth popup straight away as things stand. This needs some UX sugar for sure.

**Comment by joshuef** [comment]
@bochaco when you're trying to click the links, are you in dev mode? Could you try packaged if you didn't already. I think it might be sys-uri related...

**Comment by bochaco** [comment]
@joshuef , I did try it with packaged version but no luck.

**Comment by joshuef** [comment]
Closing as merged into `Dev`: https://github.com/joshuef/peruse/pull/49

**Pull request closed without merging**
